project:
  type: website
  output-dir: docs

website:
  title: "Βιοστατιστική – Εργαστήρια"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs/lab01.qmd
        text: Lab 1
      - href: labs/lab02.qmd
        text: Lab 2
      - href: labs/lab03.qmd
        text: Lab 3
      - href: labs/lab04.qmd
        text: Lab 4
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
